### ISSUE TITLE
Hello, might need a wiki for newbies opencomputers? 

### ISSUE THREAD

**Issue by DragonHacker1** [KaseiFR/ae2-manager#1]
Hey, again. I tried using opencomputer manual, i get everything, computer case tier 3, screen, keyboard and adapter, i connected in interface (ae2), should work this way or i need a bit more steps? Error tell me i don't have AE2 component found, i miss something?

**Comment by KaseiFR** [comment]
Did you place your adapter to touch both the AE Interface and the computer ?

**Comment by DragonHacker1** [comment]
Yes, there is a screenshot
![2019-07-12_22 11 57](https://user-images.githubusercontent.com/34381388/61152874-3b925f00-a4f2-11e9-93b0-35e8a246bfb1.png)

**Comment by KaseiFR** [comment]
What is the output of
```
require('component').list()
```
in a lua interpreter ?

**Comment by DragonHacker1** [comment]
Sorry for delay, here go.
![2019-07-12_22 41 16](https://user-images.githubusercontent.com/34381388/61154232-38996d80-a4f6-11e9-8adf-6fd9df723e05.png)
![2019-07-12_22 41 42](https://user-images.githubusercontent.com/34381388/61154252-44852f80-a4f6-11e9-88fc-c04dc5fe780e.png)
i can see adapter is online, also interface is online

**Comment by KaseiFR** [comment]
Are you using a tier 3 CPU ? You may be reaching the component limit. But I don't thing filesystems count, and you don't seem to have that many components...

I don't really know why your interface isn't being recognized. Try removing some of your hard drives, or use other AE2 blocks (a controller, disk drive, ...), preferably isolated from your main AE network.

If that still doesn't work, you can note your OC and AE2 versions and try asking to OpenComputers dev, I don't know where the issue is :(

**Comment by DragonHacker1** [comment]
I guess.. is old issue? https://github.com/MightyPirates/OpenComputers/issues/3055
Seem is for 156, but i have 153, anyway i will close until  i get new version of opencomputer, but i can ask you before to close? What ae2 version you keep using and opencomputer? and is 1.12?

**Comment by KaseiFR** [comment]
I'm currently playing Enigmatica 2 Expert, so AE2 rv6-stable-6 and OC 1.7.4.153.

And yeah, according to the issues on the OC repo, you can't interact with ME Interfaces while channels are disabled, until they release a new version.
